apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${project.artifactId}
  labels:
    run: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      run: spring
  template:
    metadata:
      labels:
        run: spring
    spec:
      containers:
        - image: kanghouchao/sutdy/spring-cloud-kubenetes:latest
          name: spring
          ports:
            - containerPort: 8080
      imagePullPolicy: Never