metadata:
  labels:
    project: ${project.artifactId}
    version: ${project.version}
spec:
  replicas: 2
  selector:
    matchLabels:
      run: spring
  template:
    metadata:
      labels:
        run: spring
    spec:
      containers:
        - image: kanghouchao/${project.artifactId}:${project.version}
          name: ${project.artifactId}
          ports:
            - containerPort: 8080
      imagePullPolicy: Never