apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${project.artifactId}
  labels:
    run: spring
spec:
  replicas: 2
  selector:
    matchLabels:
      run: spring
  template:
    metadata:
      labels:
        run: spring
    spec:
      containers:
        - image: {image.user}/${project.artifactId}:${project.version}
          name: ${project.artifactId}
          ports:
            - containerPort: 8080
      imagePullPolicy: Never