metadata:
  labels:
    project: ${project.artifactId}
    version: ${project.version}
spec:
  replicas: 2
  selector:
    matchLabels:
      project: ${project.artifactId}
      version: ${project.version}
  template:
    metadata:
      labels:
        project: ${project.artifactId}
        version: ${project.version}
    spec:
      containers:
        - image: kanghouchao/${project.artifactId}:${project.version}
          name: ${project.artifactId}
          ports:
            - containerPort: 8080
      imagePullPolicy: Never