spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: ${project.artifactId}
                port:
                  number: 8080
            path: /demo
            pathType: Prefix