spec:
  replicas: 2
  selector:
    matchLabels:
      project: ${project.artifactId}
  template:
    metadata:
      labels:
        project: ${project.artifactId}
    spec:
      containers:
        - image: kanghouchao/${project.artifactId}:${project.version}
          name: ${project.artifactId}
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ${project.artifactId}